# Generated by Django 5.1.1 on 2024-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_last_visit_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
