# Generated by Django 5.1.1 on 2024-09-14 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
