# Generated by Django 5.1.1 on 2024-09-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_patient_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_Name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('doctor_detail', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
