# Generated by Django 5.1.1 on 2024-09-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Patient_ID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Appointment_date', models.DateField()),
                ('Time_slot', models.TimeField()),
                ('Token_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Problem', models.CharField(max_length=100)),
            ],
        ),
    ]
