# Generated by Django 5.1.1 on 2024-09-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_paymenttransaction_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.appointment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
