# Generated by Django 5.1.1 on 2024-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_advance_paid_payment_total_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Token_Number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
